version: '3.8'

services:
  db:
    image: mysql:8.0
    container_name: print3d_db
    restart: always
    environment:
      MYSQL_DATABASE: print3d_db
      MYSQL_USER: print3d_user
      MYSQL_PASSWORD: print3d_password
      MYSQL_ROOT_PASSWORD: root_password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: ./backend
    container_name: print3d_backend
    restart: always
    command: >
      sh -c "python manage.py wait_for_db &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    environment:
      - DB_HOST=db
      - DB_NAME=print3d_db
      - DB_USER=print3d_user
      - DB_PASSWORD=print3d_password
      - SECRET_KEY=django-insecure-3dprintcalcsecretkeychangeit
      - DEBUG=True
      - EMAIL_HOST_USER=jaimegovea2@gmail.com
      - EMAIL_HOST_PASSWORD=zjywbkggtpckmvfa
    depends_on:
      - db

  frontend:
    build: ./frontend
    container_name: print3d_frontend
    restart: always
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://localhost:8000
    depends_on:
      - backend

volumes:
  mysql_data:
