# Generated by Django 4.2.30 on 2026-06-22 00:43

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_erp_models'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectprint',
            name='post_process_hourly_rate',
        ),
        migrations.RemoveField(
            model_name='projectprint',
            name='post_process_minutes',
        ),
        migrations.AddField(
            model_name='project',
            name='labor_hourly_rate',
            field=models.DecimalField(decimal_places=2, default=Decimal('8.00'), max_digits=10),
        ),
        migrations.AddField(
            model_name='project',
            name='labor_minutes',
            field=models.IntegerField(default=0),
        ),
    ]
